server:
  port: 8082
grpc:
  port: 7777
  enable-reflection: true

spring:
  application:
    name: grpc-start
  boot:
    admin:
      client:
        url: http://localhost:8080
# Enable logging
logging:
  level:
    root: INFO
    com.deft: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
