openapi: 3.0.1
info:
  title: Book Shop
  description: Book CRUD API.
  version: 1.0.0
servers:
  - url: /v2
paths:
  /book:
    get:
      summary: Get Books
      operationId: getBooks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add a Book
      operationId: addBook
      requestBody:
        description: Book to be added in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        200:
          description: Book Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: book
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Oathbringer
        author:
          type: string
          example: Brandon Sanderson
